#!/usr/bin/env bash
# Script that displays information about subdomains

get_subdomain_info() {
    local domain=$1
    local subdomain=$2
    local full_domain="${subdomain}.${domain}"
    
    # Use dig to get DNS information and awk to parse it
    dig "$full_domain" | awk -v sub="$subdomain" '/ANSWER SECTION:/{getline; if ($0 ~ /^[^;]/) {print "The subdomain " sub " is a " $4 " record and points to " $5}}'
}

domain=$1
subdomain=$2

if [ -z "$subdomain" ]; then
    # Display info for default subdomains
    get_subdomain_info "$domain" "www"
    get_subdomain_info "$domain" "lb-01"
    get_subdomain_info "$domain" "web-01"
    get_subdomain_info "$domain" "web-02"
else
    # Display info for specified subdomain
    get_subdomain_info "$domain" "$subdomain"
fi
