#!/usr/bin/env bash
# Display information about subdomains

get_subdomain_info() {
    domain=$1
    subdomain=$2
    
    dig_output=$(dig "$subdomain.$domain" +short)
    
    if [ -n "$dig_output" ]; then
        record_type=$(dig "$subdomain.$domain" | awk '/^[^;]/ && /IN/ {print $4; exit}')
        destination=$(echo "$dig_output" | head -n1)
        echo "The subdomain $subdomain is a $record_type record and points to $destination"
    fi
}

if [ $# -eq 1 ]; then
    get_subdomain_info "$1" "www"
    get_subdomain_info "$1" "lb-01"
    get_subdomain_info "$1" "web-01"
    get_subdomain_info "$1" "web-02"
elif [ $# -eq 2 ]; then
    get_subdomain_info "$1" "$2"
fi
